SET(LIBGP_SRC
  include/libgp/src/cov.cc
  include/libgp/src/cov_factory.cc
  include/libgp/src/cov_linear_ard.cc
  include/libgp/src/cov_linear_one.cc
  include/libgp/src/cov_matern3_iso.cc
  include/libgp/src/cov_matern5_iso.cc
  include/libgp/src/cov_noise.cc
  include/libgp/src/cov_rq_iso.cc
  include/libgp/src/cov_periodic_matern3_iso.cc
  include/libgp/src/cov_periodic.cc
  include/libgp/src/cov_se_ard.cc
  include/libgp/src/cov_se_iso.cc
  include/libgp/src/cov_sum.cc
  include/libgp/src/cov_prod.cc
  include/libgp/src/gp.cc
  include/libgp/src/gp_utils.cc
  include/libgp/src/sampleset.cc
  include/libgp/src/rprop.cc
  include/libgp/src/input_dim_filter.cc
  include/libgp/src/cg.cc
)

SET(LIBGP_INTERFACES 
  include/libgp/include/cov.h
  include/libgp/include/cov_factory.h
  include/libgp/include/cov_linear_ard.h
  include/libgp/include/cov_linear_one.h
  include/libgp/include/cov_matern3_iso.h
  include/libgp/include/cov_matern5_iso.h
  include/libgp/include/cov_noise.h
  include/libgp/include/cov_rq_iso.h
  include/libgp/include/cov_periodic_matern3_iso.h
  include/libgp/include/cov_periodic.h
  include/libgp/include/cov_se_ard.h
  include/libgp/include/cov_se_iso.h
  include/libgp/include/cov_sum.h
  include/libgp/include/cov_prod.h
  include/libgp/include/gp.h
  include/libgp/include/gp_utils.h
  include/libgp/include/sampleset.h
  include/libgp/include/rprop.h
  include/libgp/include/input_dim_filter.h
  include/libgp/include/cg.h
)
